
package ar.edu.ubp.das.indecrest.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "SucursalesWSPortService", targetNamespace = "http://services.superdiscows.das.ubp.edu.ar/", wsdlLocation = "http://localhost:8080/superdisco/sucursales.wsdl")
public class SucursalesWSPortService
    extends Service
{

    private final static URL SUCURSALESWSPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SUCURSALESWSPORTSERVICE_EXCEPTION;
    private final static QName SUCURSALESWSPORTSERVICE_QNAME = new QName("http://services.superdiscows.das.ubp.edu.ar/", "SucursalesWSPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/superdisco/sucursales.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SUCURSALESWSPORTSERVICE_WSDL_LOCATION = url;
        SUCURSALESWSPORTSERVICE_EXCEPTION = e;
    }

    public SucursalesWSPortService() {
        super(__getWsdlLocation(), SUCURSALESWSPORTSERVICE_QNAME);
    }

    public SucursalesWSPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SUCURSALESWSPORTSERVICE_QNAME, features);
    }

    public SucursalesWSPortService(URL wsdlLocation) {
        super(wsdlLocation, SUCURSALESWSPORTSERVICE_QNAME);
    }

    public SucursalesWSPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SUCURSALESWSPORTSERVICE_QNAME, features);
    }

    public SucursalesWSPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SucursalesWSPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SucursalesWSPort
     */
    @WebEndpoint(name = "SucursalesWSPortSoap11")
    public SucursalesWSPort getSucursalesWSPortSoap11() {
        return super.getPort(new QName("http://services.superdiscows.das.ubp.edu.ar/", "SucursalesWSPortSoap11"), SucursalesWSPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SucursalesWSPort
     */
    @WebEndpoint(name = "SucursalesWSPortSoap11")
    public SucursalesWSPort getSucursalesWSPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.superdiscows.das.ubp.edu.ar/", "SucursalesWSPortSoap11"), SucursalesWSPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SUCURSALESWSPORTSERVICE_EXCEPTION!= null) {
            throw SUCURSALESWSPORTSERVICE_EXCEPTION;
        }
        return SUCURSALESWSPORTSERVICE_WSDL_LOCATION;
    }

}
