
package ar.edu.ubp.das.indecrest.webservices;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "SucursalesWSPort", targetNamespace = "http://services.superdiscows.das.ubp.edu.ar/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SucursalesWSPort {


    /**
     * 
     * @param obtenerSucursalesRequest
     * @return
     *     returns ar.edu.ubp.das.indecrest.webservices.ObtenerSucursalesResponse
     */
    @WebMethod(operationName = "ObtenerSucursales")
    @WebResult(name = "ObtenerSucursalesResponse", targetNamespace = "http://services.superdiscows.das.ubp.edu.ar/", partName = "ObtenerSucursalesResponse")
    public ObtenerSucursalesResponse obtenerSucursales(
        @WebParam(name = "ObtenerSucursalesRequest", targetNamespace = "http://services.superdiscows.das.ubp.edu.ar/", partName = "ObtenerSucursalesRequest")
        ObtenerSucursalesRequest obtenerSucursalesRequest);

}
